### PR TITLE
async.waterfall instead of manual error checking

### PR DESCRIPTION
**Pull request by eugeneiiim**

### CODE REVIEW

**Comment by devony** [comment]
i agree with this in general but sometimes its hard to know how many params are returned from the previous function without a lot of effort

**Comment by eugeneiiim** [comment]
@devony i'm referring to the specific case of using async.waterfall instead of ever checking/forwarding errors explicitly in code.

**Comment by devony** [comment]
i know, im saying that usually i know the first return value of functionA, but it might return other params (usually library functions), which i need to account for in my next function which makes this kind of annoying

**Comment by Zhang** [comment]
Similar thoughts to devon, though I've been using waterfall in my routes, and it seems to be pretty effective

**Comment by danverbraganza** [comment]
I have similar feedback. This seems like a great guideline but not a hard rule, and I hope it would be administrated with benevolence grace, rather than as a blunt instrument.

Some cases where waterfall might not be appropriate are where methods more easily "bleed" parameters to each other by having them scoped nestedly, rather than each one forwarding just one result to its children.

**Comment by eugeneiiim** [comment]
@danverbraganza good point. I will update the wording to make it more of a guideline as there are definitely cases where the manual error check makes more sense.

**Pull request merged**
